package ProjetoSaulo;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;


import javax.swing.JLabel;
import java.awt.Dimension;
import javax.swing.JTextField;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gustavo
 */
public class frmAtualizarLivro extends javax.swing.JFrame {

    /**
     * Creates new form frmCadastroCliente
     */
    public frmAtualizarLivro() {
    	addWindowListener(new WindowAdapter() {
    		@Override
    		public void windowOpened(WindowEvent e) {
    		}
    	});
        initComponents();
        CarregarComboBox();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        cmbGenero = new javax.swing.JComboBox<>();
        btnGravarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ano");

        jLabel2.setText("Genero");

        jLabel3.setText("Nome");

        jLabel4.setText("Editora");

        cmbGenero.setSelectedIndex(-1);

        btnGravarCliente.setText("Atualizar");
        btnGravarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarClienteActionPerformed(evt);
            }
        });
        
        JLabel lblNewLabel = new JLabel("ATUALIZAR LIVRO");
        
        txtAutor = new JTextField();
        
        JLabel lblId = new JLabel();
        lblId.setText("Autor");
        
        lblId_2 = new JLabel();
        lblId_2.setText("ID");
        
        txtID = new JTextField();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel2)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(cmbGenero, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel1)
        								.addComponent(jLabel3))
        							.addGap(28)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(txtNome, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtAno, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel4)
        								.addComponent(lblId))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(txtAutor, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtEditora, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE))))
        					.addGap(89)
        					.addComponent(btnGravarCliente, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE))
        				.addComponent(lblNewLabel)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(lblId_2, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(txtID, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblNewLabel)
        					.addGap(17)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel3)
        						.addComponent(txtNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel1)
        						.addComponent(txtAno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel2)
        						.addComponent(cmbGenero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(7)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel4)
        						.addComponent(txtEditora, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(txtAutor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblId)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(49)
        					.addComponent(btnGravarCliente, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblId_2)
        				.addComponent(txtID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarClienteActionPerformed
    AlterarLivro();    
    }//GEN-LAST:event_btnGravarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAtualizarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAtualizarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAtualizarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAtualizarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAtualizarLivro().setVisible(true);
            }
        });
    }
    
    
       Vector<Integer> id_genero = new Vector<Integer>();
    public void CarregarComboBox(){
        ResultSet rs; 
        try{
            LivroDAO objlivrodao = new LivroDAO();
            rs = objlivrodao.carregarCBX();
            while(rs.next()){
                id_genero.addElement(rs.getInt(1));
                cmbGenero.addItem(rs.getString(2));
            }
        }catch (SQLException erro){
            JOptionPane.showMessageDialog(null, "Carregar ComboBox de Generos: " + erro);
        }
    }
    
    
    private void AlterarLivro(){ 
        int ID_livro; 
        String Nome_livro, Autor_livro, Editora_livro;
        int Ano_livro, cod_genero;

        ID_livro = Integer.parseInt(txtID.getText()); 
        Nome_livro = txtNome.getText(); 
        cod_genero = id_genero.get(cmbGenero.getSelectedIndex());
        Autor_livro = txtAutor.getText(); 
        Ano_livro =  Integer.parseInt(txtAno.getText());
        Editora_livro = txtEditora.getText();

        LivroDTO objLivroDTO = new LivroDTO(); 
        objLivroDTO.setID_livro(ID_livro); 
        objLivroDTO.setNome_livro(Nome_livro); 
        objLivroDTO.setGenero_FK_livro(cod_genero); 
        objLivroDTO.setAutor_livro(Autor_livro); 
        objLivroDTO.setAno_livro(Ano_livro); 
        objLivroDTO.setEditora_livro(Editora_livro); 

        LivroDAO objLivroDAO = new LivroDAO(); 
        objLivroDAO.alterarLivro(objLivroDTO); 
 } 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravarCliente;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtAno;
    private JTextField txtAutor;
    private JLabel lblId_2;
    private JTextField txtID;
}
